=== saveligulas/University/Library/LibraryV2/src/main/resources/items.dtd
<!ELEMENT library_items (books)>
<!ELEMENT books (book)>
<!ELEMENT journals (journal)>
<!ELEMENT book (info)>
<!ELEMENT journal (info)>
<!ELEMENT info (copy_number, title, publisher, intellectual_owner, description, categories)>
<!ATTLIST info identifier ID #REQUIRED>
<!ELEMENT copy_number (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT intellectual_owner (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT categories (category+)>
<!ELEMENT category (#PCDATA)>

=== saveligulas/University/Library/LibraryV2/src/main/resources/items.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE library_items SYSTEM "items.dtd">
<library_items>
    <books>
        <book>
            <info identifier="ISBN-1000">
                <copy_number></copy_number>
                <title></title>
                <publisher></publisher>
                <intellectual_owner></intellectual_owner>
                <description></description>
                <categories>
                    <category></category>
                </categories>
            </info>
        </book>
    </books>
</library_items>
