=== saveligulas/University/src/main/resources/archery_tournament.dtd
[<!ELEMENT archery_tournament (type|target|point_sheet|course)*>
        <!ATTLIST archery_tournament
                xmlns:xs CDATA #REQUIRED>
        <!ELEMENT type (#PCDATA)>
        <!ATTLIST type
                id ID #REQUIRED
                point_sheet_id IDREF #REQUIRED>
        <!ELEMENT target (#PCDATA)>
        <!ATTLIST target
                id ID #REQUIRED
                type_id IDREF #REQUIRED>
        <!ELEMENT point_sheet (xs:simpleType)*>
        <!ATTLIST point_sheet
                id ID #REQUIRED>
        <!ELEMENT xs:simpleType (xs:list)*>
        <!ATTLIST xs:simpleType
                name CDATA #REQUIRED>
        <!ELEMENT xs:list (#PCDATA)>
        <!ATTLIST xs:list
                itemType IDREF #REQUIRED>
        <!ELEMENT course (name|xs:simpleType)*>
        <!ATTLIST course
                id ID #REQUIRED>
        <!ELEMENT name (#PCDATA)>]

=== saveligulas/University/src/main/resources/3DArcheryCourses.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE archery_tournament SYSTEM "archery_tournament.dtd">
<archery_tournament xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <type id="boar" point_sheet_id="boar_points">Boar</type>
    <type id="pig" point_sheet_id="pig_points">Pig</type>
    <type id="hawk" point_sheet_id="hawk_points">Hawk</type>

    <target id="target-001" type_id="boar">Target 1</target>
    <target id="target-002" type_id="pig">Target 2</target>
    <target id="target-003" type_id="hawk">Target 3</target>

    <point_sheet id="boar_points">
        <xs:simpleType name="points">
            <xs:list itemType="xs:integer">
            </xs:list>
        </xs:simpleType>
    </point_sheet>
    <point_sheet id="pig_points">
        <xs:simpleType name="points">
            <xs:list itemType="xs:integer">
            </xs:list>
        </xs:simpleType>
    </point_sheet>
    <point_sheet id="hawk_points">
        <xs:simpleType name="points">
            <xs:list itemType="xs:integer">
            </xs:list>
        </xs:simpleType>
    </point_sheet>

    <course id="01">
        <name>Test Course</name>
        <target_list>
    </course>
</archery_tournament>
